
--change users from super users to normal users
SELECT
    'alter user '||usename||' NOCREATEUSER;'
FROM
    pg_user
WHERE
    usename LIKE 'laptop%';

ALTER USER laptop2 NOCREATEUSER;
ALTER USER laptop17 NOCREATEUSER;
ALTER USER laptop18 NOCREATEUSER;
ALTER USER laptop19 NOCREATEUSER;
ALTER USER laptop20 NOCREATEUSER;
ALTER USER laptop8 NOCREATEUSER;
ALTER USER laptop7 NOCREATEUSER;
ALTER USER laptop13 NOCREATEUSER;
ALTER USER laptop5 NOCREATEUSER;
ALTER USER laptop14 NOCREATEUSER;
ALTER USER laptop3 NOCREATEUSER;
ALTER USER laptop15 NOCREATEUSER;
ALTER USER laptop12 NOCREATEUSER;
ALTER USER laptop10 NOCREATEUSER;
ALTER USER laptop9 NOCREATEUSER;
ALTER USER laptop1 NOCREATEUSER;
ALTER USER laptop6 NOCREATEUSER;
ALTER USER laptop11 NOCREATEUSER;
ALTER USER laptop16 NOCREATEUSER;
ALTER USER laptop4 NOCREATEUSER;
ALTER USER laptop17_2 NOCREATEUSER;

SELECT
    *
FROM
    pg_user
WHERE
    usename LIKE 'laptop%';
